name: Python Workflow

on:
  workflow_dispatch:

  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "pypy3.9"
      - run: python my_script.py
